### ISSUE TITLE
Change footer stating DO hosting incorrectly

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/pgr_system#57] opened 2018-09-03 10:25 UTC

**Comment by pet1330** [comment] 2018-09-03 10:47
Duplicate of pet1330/pgr_system#43

**Closed by pet1330** 2018-09-03 10:47 UTC
Labels: bug

**Comment by pet1330** [comment] 2018-09-03 11:47
See https://github.com/pet1330/pgr_system/issues/43#issuecomment-365648181. Either we can leave the footer in to try and cover the cost of hosting between June 2017 and Feb 2018  or I can submit an expenses claim for the cost of hosting between those dates

**Comment by pet1330** [comment] 2018-09-03 11:55
I've corrected it, so that it is no longer wrong :smiley:
